apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
